version: "3"
services: 
  linux: 
    container_name: 'ubuntu-linux'
    image: "mediasoup"
    restart: "always"
    tty: true
    ports:
      - "3000:3000"
      - "2000-2020:2000-2020"
    volumes:
       - ./:/usr/code